tslib: fix gcc-14 build
temporary fix until tslib can be updated

fixes missing header

src/ts_reconfig.c: In function 'ts_reconfig':
src/ts_reconfig.c:43:9: error: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
   43 |         memset(ts, 0, sizeof(struct tsdev));
      |         ^~~~~~
src/ts_reconfig.c:21:1: note: include '<string.h>' or provide a declaration of 'memset'
   20 | #include "tslib-private.h"
  +++ |+#include <string.h>
   21 |
src/ts_reconfig.c:43:9: warning:incompatible implicit declaration of built-in function 'memset' [-Wbuiltin-declaration-mismatch]
   43 |         memset(ts, 0, sizeof(struct tsdev));
      |         ^~~~~~
src/ts_reconfig.c:43:9: note: include '<string.h>' or provide a declaration of 'memset'