Revert "cmake: disable openssl dependency"
This reverts commit 092ee90456c336018d7feec3ce73279864ab53a6.

On CoreELEC we download libdvd* packages by Kodi itself to match version without changing version in separate packages. That's why cmake must be build with openssl to alow downloading files from https.

[3/1599] Creating directories for 'dvdcss'
[4/1599] Performing download step (download, verify and extract) for 'dvdcss'
FAILED: build/libdvd/src/dvdcss-stamp/dvdcss-download /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/dvdcss-download
cd /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/download-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/verify-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -P /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/extract-dvdcss.cmake && /home/user/LibreELEC/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/toolchain/bin/cmake -E touch /home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/libdvd/src/dvdcss-stamp/dvdcss-download
-- Downloading...
   dst='/home/user/CoreELEC.20/build.CoreELEC-Amlogic-ng.arm-20/build/kodi-b087ce63402ac70e339b981aceba1baa61489313/.armv8a-libreelec-linux-gnueabihf/build/download/libdvdcss-1.4.3-Next-Nexus-Alpha2.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/xbmc/libdvdcss/archive/1.4.3-Next-Nexus-Alpha2.tar.gz'
CMake Error at dvdcss-stamp/download-dvdcss.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/xbmc/libdvdcss/archive/1.4.3-Next-Nexus-Alpha2.tar.gz' failed
          status_code: 1
          status_string: "Unsupported protocol"
          log:
          --- LOG BEGIN ---
          Protocol "https" not supported or disabled in libcurl

  Closing connection -1

          --- LOG END ---