Revert "pygobject: bump to 3.42.1 and switch to meson"
This reverts commit e189b261176b72a3ff9666caad851a47a07be934.

Problemsn when actually using it: 
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi.repository'