spirv-tools: fix host build with gcc 12
spirv-tools:host fails to build on Debian Bookworm with gcc 12.2 due to a
(likely false-positive) warning in source/val/validate_decorations.cpp:

/usr/include/c++/12/bits/new_allocator.h:158:33: error: 'void operator delete(void*, std::size_t)' called on pointer '<unknown>' with nonzero offset [1, 9223372036854775804] [-Werror=free-nonheap-object]
  158 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |

Just disable Werror on host builds to turn this into a normal warning
and let the build succeed.

Signed-off-by: Matthias Reichl <hias@horus.com>