EmuELEC addon build fixes (#285)
* emulationstation-addon: add gcc target dependency

gcc package provides libgomp library

* mupen64plus-nx: fix Amlogic builds

PKG_URL was set before if block, it downloaded wrong version

* commander-genius: add Python3 target dependency

fixes following error:
error: 'PyUnicode_AsUTF8' was not declared in this scope

* README: add build dependency for addon build

xmlstarlet is needed for emuelec-addon.sh build


Fixes #228