linux (Allwinner): rebase and update patches for 6.11
The following changes were introduced in 6.11-rc1 and 6.11-rc7

only pass 3 variables to
- of: remove internal arguments from of_property_for_each_u32()
- https://github.com/torvalds/linux/commit/9722c3b66e21ff08aec570d02a97d331087fd70f

6.11-rc7 has refactored drm https://github.com/torvalds/linux/commit/9da7ec9b19d8c1ad4f44e459fa5f93ad7a117dcd
resulting in the following compile error.

build.LibreELEC-H6.aarch64-13.0-devel/toolchain/bin/aarch64-libreelec-linux-gnu-ld: drivers/gpu/drm/sun4i/sun8i_dw_hdmi.o: in function `sun8i_dw_hdmi_bind':
build.LibreELEC-H6.aarch64-13.0-devel/build/linux-6.11-rc7/drivers/gpu/drm/sun4i/sun8i_dw_hdmi.c:394:(.text+0x73c): undefined reference to `drm_bridge_connector_init'

Co-authored-by: Jernej Skrabec <jernej.skrabec@gmail.com>